#!/usr/bin/env python3

from __future__ import annotations

import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

EXCLUDED_NAMES = {
    ".git",
    ".hg",
    ".svn",
    ".DS_Store",
    "node_modules",
    "dist",
    "build",
    "coverage",
    ".next",
    ".nuxt",
    ".out",
    ".cache",
    ".parcel-cache",
    ".turbo",
    ".vercel",
    "tmp",
    "temp",
    "vendor",
    "target",
    "bin",
    "obj",
    "DerivedData",
    ".venv",
    "venv",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    "storybook-static",
    "playwright-report",
    "test-results",
}
EXCLUDED_SUFFIXES = (".log", ".tsbuildinfo")
GENERATED_COMMENT = (
    "<!-- Generated by monorepo file tree skill. Do not manually edit unless you also update the generator contract. -->"
)
FILE_TREE_SECTION = """## File tree documentation

This repository maintains generated file tree references for navigation and agent orientation.

- Root overview: `monorepo-filetree.md`
- Per-app overviews: `apps/<app-name>/doc/filetree.md`

When repository structure changes materially, update these generated documents to keep them in sync.
"""
DEFAULT_AGENTS_CONTENT = """# AGENTS.md

## Repository guidance

This repository contains a monorepo with app-specific file tree documentation.

## File tree documentation

This repository maintains generated file tree references for navigation and agent orientation.

- Root overview: `monorepo-filetree.md`
- Per-app overviews: `apps/<app-name>/doc/filetree.md`

When repository structure changes materially, update these generated documents to keep them in sync.

## Expectations for agents

- Keep file tree documentation in sync when repository structure changes materially
- Prefer updating existing generated file tree docs rather than creating alternate copies
- Do not hand-edit generated sections unless the generation contract explicitly allows it
"""


class BlockingError(RuntimeError):
    pass


@dataclass(frozen=True)
class WriteResult:
    path: Path
    status: str


@dataclass(frozen=True)
class AppResult:
    name: str
    doc_dir_created: bool
    file_result: WriteResult | None
    error: str | None


def run_command(command: list[str], cwd: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(command, cwd=cwd, capture_output=True, text=True, check=False)


def resolve_repo_root() -> Path:
    script_dir = Path(__file__).resolve().parent
    result = run_command(["git", "rev-parse", "--show-toplevel"], cwd=script_dir)
    if result.returncode != 0:
        raise BlockingError(f"Blocking error: could not resolve repo root from {script_dir}: {result.stderr.strip()}")
    return Path(result.stdout.strip()).resolve()


def validate_apps_root(repo_root: Path) -> Path:
    apps_root = repo_root / "apps"
    if not apps_root.is_dir():
        raise BlockingError(f"Blocking error: expected apps/ at {apps_root}, but it does not exist.")
    return apps_root


def discover_apps(apps_root: Path) -> list[Path]:
    return sorted((child for child in apps_root.iterdir() if child.is_dir()), key=lambda child: child.name.lower())


def should_exclude(relative_path: Path) -> bool:
    name = relative_path.name
    if name in EXCLUDED_NAMES:
        return True
    if any(name.endswith(suffix) for suffix in EXCLUDED_SUFFIXES):
        return True
    parts = relative_path.parts
    for index in range(len(parts) - 1):
        if parts[index] == "public" and parts[index + 1] == "build":
            return True
    return False


def visible_children(directory: Path, scope_root: Path, virtual_files: set[Path]) -> list[tuple[str, bool, Path | None]]:
    children: list[tuple[str, bool, Path | None]] = []
    seen_names: set[str] = set()

    for child in directory.iterdir():
        relative_path = child.relative_to(scope_root)
        if should_exclude(relative_path):
            continue
        children.append((child.name, child.is_dir(), child))
        seen_names.add(child.name)

    directory_relative = directory.relative_to(scope_root)
    for virtual_file in sorted(virtual_files):
        if virtual_file.parent == directory_relative and virtual_file.name not in seen_names:
            children.append((virtual_file.name, False, None))

    children.sort(key=lambda item: (0 if item[1] else 1, item[0].lower(), item[0]))
    return children


def has_visible_children(directory: Path, scope_root: Path, virtual_files: set[Path]) -> bool:
    return bool(visible_children(directory, scope_root, virtual_files))


def render_tree(scope_root: Path, label: str, max_depth: int, virtual_files: set[Path] | None = None) -> str:
    virtual_files = virtual_files or set()
    lines = [label]

    def walk(directory: Path, prefix: str, depth: int) -> list[str]:
        entries = visible_children(directory, scope_root, virtual_files)
        output: list[str] = []
        for index, (name, is_dir, child_path) in enumerate(entries):
            is_last = index == len(entries) - 1
            connector = "└── " if is_last else "├── "
            display_name = f"{name}/" if is_dir else name
            output.append(f"{prefix}{connector}{display_name}")
            next_prefix = prefix + ("    " if is_last else "│   ")
            if not is_dir or child_path is None:
                continue
            if depth >= max_depth:
                if has_visible_children(child_path, scope_root, virtual_files):
                    output.append(f"{next_prefix}└── …")
                continue
            output.extend(walk(child_path, next_prefix, depth + 1))
        return output

    lines.extend(walk(scope_root, "", 1))
    return "\n".join(lines)


def render_root_markdown(repo_root: Path, apps: list[Path], tree: str) -> str:
    if apps:
        apps_section = "\n\n".join(
            [
                f"### apps/{app.name}\n\n- Detailed tree: `apps/{app.name}/doc/filetree.md`"
                for app in apps
            ]
        )
    else:
        apps_section = "No app directories were discovered under `apps/`."

    return (
        f"{GENERATED_COMMENT}\n\n"
        "# Monorepo File Tree\n\n"
        "## Purpose\n\n"
        "This document provides a structural overview of the monorepo.\n\n"
        "## Generation rules\n\n"
        "- Generated automatically\n"
        "- Source of truth: current repository structure\n"
        "- Excludes generated/vendor/noisy paths\n"
        "- Per-app detailed trees live in each app's `doc/filetree.md`\n\n"
        "## Top-level structure\n\n"
        "```text\n"
        f"{tree}\n"
        "```\n\n"
        "## Apps\n\n"
        f"{apps_section}\n"
    )


def render_app_markdown(app_name: str, app_relative_path: str, tree: str) -> str:
    return (
        f"{GENERATED_COMMENT}\n\n"
        f"# File Tree: {app_name}\n\n"
        "## Purpose\n\n"
        f"This document provides a structural overview of the `{app_name}` app.\n\n"
        "## Path\n\n"
        f"`{app_relative_path}`\n\n"
        "## Notes\n\n"
        "- Generated automatically\n"
        "- Excludes generated/vendor/noisy paths\n"
        "- Intended for navigation and agent orientation\n\n"
        "## Tree\n\n"
        "```text\n"
        f"{tree}\n"
        "```\n"
    )


def write_if_changed(path: Path, content: str) -> WriteResult:
    existed = path.exists()
    if existed:
        existing = path.read_text(encoding="utf-8")
        if existing == content:
            return WriteResult(path=path, status="unchanged")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return WriteResult(path=path, status="updated" if existed else "created")


def is_file_tree_heading(line: str) -> bool:
    return line.startswith("## ") and "file tree" in line.lower()


def upsert_file_tree_section(markdown: str) -> str:
    if not markdown.strip():
        return DEFAULT_AGENTS_CONTENT

    lines = markdown.splitlines()
    section_start = None
    section_end = None
    for index, line in enumerate(lines):
        if is_file_tree_heading(line):
            section_start = index
            for next_index in range(index + 1, len(lines)):
                if lines[next_index].startswith("## "):
                    section_end = next_index
                    break
            if section_end is None:
                section_end = len(lines)
            break

    replacement_lines = FILE_TREE_SECTION.strip().splitlines()
    if section_start is None:
        trimmed = markdown.rstrip()
        separator = "\n\n" if trimmed else ""
        return f"{trimmed}{separator}{FILE_TREE_SECTION.strip()}\n"

    updated_lines = lines[:section_start] + replacement_lines + lines[section_end:]
    return "\n".join(updated_lines).rstrip() + "\n"


def ensure_agents(repo_root: Path) -> WriteResult:
    agents_path = repo_root / "AGENTS.md"
    if not agents_path.exists():
        return write_if_changed(agents_path, DEFAULT_AGENTS_CONTENT)

    updated = upsert_file_tree_section(agents_path.read_text(encoding="utf-8"))
    return write_if_changed(agents_path, updated)


def relative_path(path_value: Path | str, repo_root: Path) -> str:
    root = repo_root.resolve()
    path = Path(path_value)
    if not path.is_absolute():
        path = root / path
    path = path.resolve()

    try:
        return path.relative_to(root).as_posix()
    except ValueError as exc:
        raise ValueError(f"Path {path} is outside repo root {root}") from exc


def format_write_result(result: WriteResult, repo_root: Path) -> str:
    return f"{result.status}: {relative_path(result.path, repo_root)}"


def main() -> int:
    try:
        repo_root = resolve_repo_root()
        apps_root = validate_apps_root(repo_root)
        apps = discover_apps(apps_root)

        try:
            agents_result = ensure_agents(repo_root)
        except OSError as exc:
            raise BlockingError(f"Blocking error: failed to write {repo_root / 'AGENTS.md'}: {exc}") from exc

        app_results: list[AppResult] = []
        for app in apps:
            app_relative = relative_path(app, repo_root)
            doc_dir = app / "doc"
            doc_dir_created = False
            try:
                if not doc_dir.exists():
                    doc_dir.mkdir(parents=True, exist_ok=True)
                    doc_dir_created = True
                tree = render_tree(
                    app,
                    label=f"{app_relative}/",
                    max_depth=6,
                    virtual_files={Path("doc/filetree.md")},
                )
                markdown = render_app_markdown(app.name, app_relative, tree)
                file_result = write_if_changed(doc_dir / "filetree.md", markdown)
                app_results.append(AppResult(app.name, doc_dir_created, file_result, None))
            except Exception as exc:
                app_results.append(AppResult(app.name, doc_dir_created, None, str(exc)))

        try:
            root_tree = render_tree(
                repo_root,
                label=f"{repo_root.name}/",
                max_depth=4,
                virtual_files={Path("monorepo-filetree.md")},
            )
            root_markdown = render_root_markdown(repo_root, apps, root_tree)
            root_result = write_if_changed(repo_root / "monorepo-filetree.md", root_markdown)
        except OSError as exc:
            raise BlockingError(f"Blocking error: failed to write {repo_root / 'monorepo-filetree.md'}: {exc}") from exc

        print(format_write_result(agents_result, repo_root))
        print(format_write_result(root_result, repo_root))
        for app_result in app_results:
            prefix = f"{app_result.name}: "
            if app_result.error:
                print(f"partial failure: {prefix}{app_result.error}")
                continue
            if app_result.doc_dir_created:
                print(f"created directory: {relative_path(repo_root / 'apps' / app_result.name / 'doc', repo_root)}")
            if app_result.file_result is not None:
                print(format_write_result(app_result.file_result, repo_root))

        failed_apps = [result.name for result in app_results if result.error]
        if failed_apps:
            print(f"partial failure: app file tree generation failed for {', '.join(failed_apps)}", file=sys.stderr)
            return 1
        return 0
    except BlockingError as exc:
        print(str(exc), file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
